# Generated by Django 5.1.7 on 2025-04-14 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_post_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
    ]
